# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Deploy default.xml to sel4test-manifest after successful runs.

name: Deploy

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  # allow manual trigger
  workflow_dispatch:

  # allow explict trigger from other repos when dependencies have changed
  repository_dispatch:
    types: [deps-update]

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: akifejaz/ci-actions/repo-checkout@bpi-f3-ci
      with:
        manifest_repo: sel4test-manifest
        manifest: master.xml

  sim:
    name: Simulation
    needs: code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [armv7a, armv8a, nehalem, rv32imac, rv64imac]
        compiler: [gcc, clang]
    steps:
    - uses: akifejaz/ci-actions/sel4test-sim@bpi-f3-ci
      with:
        xml: ${{ needs.code.outputs.xml }}
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}

  hw-build:
    name: HW Build
    needs: code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # There is no "rv32imac" hardware yet.
        march: [armv7a, armv8a, nehalem, rv64imac]
        compiler: [gcc, clang]
    steps:
    - name: Build
      uses: akifejaz/ci-actions/sel4test-hw@bpi-f3-ci
      with:
        xml: ${{ needs.code.outputs.xml }}
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-images.tar.gz'

  the_matrix:
    name: Matrix
    needs: hw-build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - id: matrix
      uses: akifejaz/ci-actions/sel4test-hw-matrix@bpi-f3-ci

  hw-run:
    name: HW Run
    if: ${{ github.repository_owner == 'seL4' || contains(github.ref, 'bpi-f3') }}
    runs-on: ${{ contains(fromJson(needs.the_matrix.outputs.matrix).include[strategy.job-index].platform, 'BANANAPI_F3') && 'self-hosted' || 'ubuntu-latest' }}
    needs: [the_matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.the_matrix.outputs.matrix) }}
    # do not run concurrently with other workflows, but do run concurrently in the build matrix
    concurrency: hw-run-${{ strategy.job-index }}
    steps:
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: images-${{ matrix.march }}-${{ matrix.compiler }}
      - name: Run
        uses: akifejaz/ci-actions/sel4test-hw-run@bpi-f3-ci
        with:
          platform: ${{ matrix.platform }}
          compiler: ${{ matrix.compiler }}
          mode: ${{ matrix.mode }}
          index: ${{ strategy.job-index }}
          lava_server: ${{ secrets.LAVA_SERVER }}
          lava_api_token: ${{ secrets.LAVA_API_TOKEN }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
          LAVA_SERVER: ${{ secrets.LAVA_SERVER }}
          LAVA_API_TOKEN: ${{ secrets.LAVA_API_TOKEN }}
          LAVA_SERVERIP: ${{ secrets.LAVA_SERVERIP || '192.168.1.1' }}
          LAVA_CLIENTIP: ${{ secrets.LAVA_CLIENTIP || '192.168.1.100' }}


  deploy:
    name: Deploy manifest
    if: ${{ github.repository_owner == 'seL4' }}
    runs-on: ubuntu-22.04
    needs: [code, hw-run]
    steps:
    - name: Deploy
      uses: akifejaz/ci-actions/manifest-deploy@bpi-f3-ci
      with:
        xml: ${{ needs.code.outputs.xml }}
        manifest_repo: sel4test-manifest
      env:
        GH_SSH: ${{ secrets.CI_SSH }}
